import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowLeft, CheckCircle2, ShieldCheck, UserPlus } from "lucide-react";
import { useState } from "react";
import { SuperAdminShell, SuperCard } from "../../../components/SuperAdminShell";

export const Route = createFileRoute("/super-admin/utilizadores/novo")({ component: NovoUtilizadorGlobal });

const profiles=["Administrador Municipal","Técnico","Fiscal","Financeiro"];
function NovoUtilizadorGlobal(){
 const [created,setCreated]=useState(false); const [name,setName]=useState(""); const [email,setEmail]=useState(""); const [profile,setProfile]=useState("Administrador Municipal"); const [municipality,setMunicipality]=useState("Lichinga"); const [status,setStatus]=useState("Activo");
 if(created)return <SuperAdminShell title="Utilizador criado" subtitle="A preparação da conta foi concluída."><SuperCard className="mx-auto max-w-2xl p-8 text-center"><div className="mx-auto flex h-14 w-14 items-center justify-center rounded-full bg-emerald-50 text-emerald-600"><CheckCircle2/></div><h2 className="mt-5 text-2xl font-bold">{name}</h2><p className="mt-2 text-sm text-slate-500">{profile} · {municipality}</p><p className="mt-1 text-sm text-slate-500">{email}</p><Link to="/super-admin/utilizadores" className="mt-7 inline-flex rounded-xl bg-sky-600 px-5 py-3 text-sm font-semibold text-white">Voltar aos utilizadores</Link></SuperCard></SuperAdminShell>;
 return <SuperAdminShell title="Novo utilizador" subtitle="Criar uma conta global e definir o seu âmbito de acesso."><Link to="/super-admin/utilizadores" className="mb-6 inline-flex items-center gap-2 text-sm text-slate-500 hover:text-sky-600"><ArrowLeft className="h-4 w-4"/> Utilizadores</Link><SuperCard className="mx-auto max-w-4xl p-7"><div className="flex items-start gap-4 border-b border-slate-100 pb-6"><div className="flex h-12 w-12 items-center justify-center rounded-xl bg-sky-50 text-sky-600"><UserPlus/></div><div><h2 className="text-xl font-bold">Dados da conta</h2><p className="mt-1 text-sm text-slate-500">O acesso efectivo será criado no Supabase Auth na fase de integração.</p></div></div><div className="mt-7 grid gap-5 md:grid-cols-2">
<Field label="Nome completo *" value={name} setValue={setName} placeholder="Nome completo"/><Field label="Email *" value={email} setValue={setEmail} placeholder="utilizador@municipio.gov.mz"/><Field label="Contacto" placeholder="+258 ..."/><Select label="Perfil" value={profile} setValue={setProfile} options={profiles}/><Select label="Município" value={municipality} setValue={setMunicipality} options={["Lichinga","Pemba"]}/><Field label="Posto administrativo" placeholder="Opcional"/><Select label="Estado" value={status} setValue={setStatus} options={["Activo","Suspenso"]}/>
</div><div className="mt-6 rounded-xl border border-sky-100 bg-sky-50 p-4 text-sm leading-6 text-sky-900"><ShieldCheck className="mr-2 inline h-4 w-4"/><b>Regra:</b> o Super Administrador pode gerir contas globalmente. Perfis municipais devem ter município atribuído; o posto pode restringir ainda mais o acesso.</div><div className="mt-7 flex justify-end gap-3"><Link to="/super-admin/utilizadores" className="rounded-xl border border-slate-200 px-5 py-3 text-sm font-semibold">Cancelar</Link><button type="button" disabled={!name||!email} onClick={()=>setCreated(true)} className="rounded-xl bg-sky-600 px-5 py-3 text-sm font-semibold text-white disabled:opacity-40">Criar utilizador</button></div></SuperCard></SuperAdminShell>;
}
function Field({label,value,setValue,placeholder}:{label:string;value?:string;setValue?:(v:string)=>void;placeholder:string}){return <label className="text-sm font-medium">{label}<input value={value} onChange={e=>setValue?.(e.target.value)} placeholder={placeholder} className="mt-2 h-11 w-full rounded-xl border border-slate-300 px-3 outline-none focus:border-sky-500"/></label>}
function Select({label,value,setValue,options}:{label:string;value:string;setValue:(v:string)=>void;options:string[]}){return <label className="text-sm font-medium">{label}<select value={value} onChange={e=>setValue(e.target.value)} className="mt-2 h-11 w-full rounded-xl border border-slate-300 px-3">{options.map(o=><option key={o}>{o}</option>)}</select></label>}
