import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowLeft, ArrowRight, Check, FileCheck2, UserRound } from "lucide-react";
import { MobiGestShell, Card } from "../../../components/MobiGestShell";
export const Route=createFileRoute("/veiculos/$id/transferir")({component:Transferir});
function Transferir(){const {id}=Route.useParams();return <MobiGestShell title="Transferência de propriedade" subtitle="Registo controlado da mudança de proprietário">
 <Link to="/veiculos/$id" params={{id}} className="mb-6 inline-flex items-center gap-2 text-sm text-slate-500 hover:text-sky-600"><ArrowLeft className="h-4 w-4"/>Voltar ao veículo</Link>
 <div className="mx-auto max-w-4xl"><Card className="p-7">
  <div className="flex items-start gap-4"><div className="flex h-11 w-11 items-center justify-center rounded-xl bg-sky-50 text-sky-600"><FileCheck2/></div><div><h2 className="text-xl font-bold">Transferir {id}</h2><p className="mt-1 text-sm text-slate-500">O proprietário actual permanece no histórico do veículo.</p></div></div>
  <div className="mt-7 grid gap-4 md:grid-cols-3 items-center"><Owner title="Actual" name="Alberto Manuel" doc="BI 11020345LA"/><div className="mx-auto rounded-full bg-slate-100 p-3"><ArrowRight className="text-slate-400"/></div><div className="rounded-xl border border-sky-200 bg-sky-50 p-4"><p className="text-xs font-semibold uppercase text-sky-600">Novo</p><p className="mt-2 font-semibold">A preencher</p><p className="text-xs text-slate-500">Dados do novo proprietário</p></div></div>
  <div className="my-8 border-t border-slate-100 pt-7"><h3 className="font-semibold">Dados do novo proprietário</h3><div className="mt-5 grid gap-4 md:grid-cols-2">{["Nome completo","Tipo de documento","Número do documento","NUIT (opcional)","Telefone","Morada"].map(x=><label className="text-sm font-medium" key={x}>{x}<input className="mt-2 h-11 w-full rounded-xl border border-slate-300 px-3 outline-none focus:border-sky-500"/></label>)}</div><label className="mt-4 block text-sm font-medium">Observações<textarea className="mt-2 min-h-24 w-full rounded-xl border border-slate-300 p-3 outline-none focus:border-sky-500"/></label></div>
  <div className="rounded-xl bg-slate-50 p-4 text-sm text-slate-600"><b>Atenção:</b> a transferência deve ser confirmada com a documentação exigida pelo município antes de alterar a propriedade.</div>
  <div className="mt-6 flex flex-wrap justify-end gap-3"><Link to="/veiculos/$id" params={{id}} className="rounded-xl border border-slate-200 px-5 py-3 text-sm font-semibold">Cancelar</Link><button className="inline-flex items-center gap-2 rounded-xl bg-sky-600 px-5 py-3 text-sm font-semibold text-white"><Check className="h-4 w-4"/>Confirmar transferência</button></div>
 </Card></div></MobiGestShell>}
function Owner({title,name,doc}:{title:string;name:string;doc:string}){return <div className="rounded-xl border border-slate-200 p-4"><p className="text-xs font-semibold uppercase tracking-wide text-slate-400">{title}</p><div className="mt-3 flex items-center gap-3"><div className="flex h-9 w-9 items-center justify-center rounded-full bg-slate-100"><UserRound className="h-4 w-4"/></div><div><p className="text-sm font-semibold">{name}</p><p className="text-xs text-slate-500">{doc}</p></div></div></div>}
