import { RouteIndexBoundary } from "../../components/RouteIndexBoundary";
import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowLeft, Bike, Edit3, Phone, UserRound } from "lucide-react";
import { MobiGestShell, Card } from "../../components/MobiGestShell";
export const Route=createFileRoute("/proprietarios/$id")({component: PerfilRouteBoundary});
function Perfil(){const{id}=Route.useParams();return <MobiGestShell title="Perfil do proprietário" subtitle="Dados cadastrais e veículos associados"><Link to="/proprietarios" className="mb-6 inline-flex items-center gap-2 text-sm text-slate-500 hover:text-sky-600"><ArrowLeft className="h-4 w-4"/>Proprietários</Link><div className="grid gap-6 lg:grid-cols-[380px_1fr]"><Card className="p-6"><div className="flex items-center gap-4"><div className="flex h-16 w-16 items-center justify-center rounded-full bg-sky-50 text-sky-600"><UserRound className="h-8 w-8"/></div><div><h2 className="text-xl font-bold">{id}</h2><p className="text-sm text-slate-500">Proprietário registado</p></div></div><div className="mt-7 space-y-4">{[["Documento","BI 11020345LA"],["Telefone","+258 84 000 0000"],["Morada","Lichinga, Niassa"],["NUIT","—"]].map(x=><div key={x[0]}><p className="text-xs text-slate-400">{x[0]}</p><p className="mt-1 text-sm font-medium">{x[1]}</p></div>)}</div><div className="mt-6 flex gap-2"><Link to="/proprietarios/$id/editar" params={{id}} className="inline-flex items-center gap-2 rounded-xl border border-slate-200 px-4 py-2.5 text-sm font-semibold"><Edit3 className="h-4 w-4"/>Editar</Link><button className="inline-flex items-center gap-2 rounded-xl border border-slate-200 px-4 py-2.5 text-sm font-semibold"><Phone className="h-4 w-4"/>Contacto</button><Link to="/proprietarios/$id/documentos" params={{id}} className="inline-flex items-center gap-2 rounded-xl border border-slate-200 px-4 py-2.5 text-sm font-semibold">Documentos</Link></div></Card><Card className="p-6"><div className="flex items-center justify-between"><div><h3 className="font-semibold">Veículos associados</h3><p className="mt-1 text-xs text-slate-500">Histórico de propriedade ligado a este cidadão.</p></div><span className="rounded-full bg-slate-100 px-3 py-1 text-xs font-semibold">2 veículos</span></div><div className="mt-5 space-y-3">{[["Honda CB 125","MZ-LIC-004821","Activa"],["TVS HLX 125","MZ-LIC-004818","Pendente"]].map(x=><Link to="/veiculos/$id" params={{id:x[1]}} className="flex items-center justify-between rounded-xl border border-slate-200 p-4 hover:border-sky-200" key={x[1]}><div className="flex items-center gap-3"><Bike className="text-sky-600"/><div><p className="font-semibold">{x[0]}</p><p className="text-xs text-slate-500">{x[1]}</p></div></div><span className={`rounded-full px-2.5 py-1 text-xs font-semibold ${x[2]==="Activa"?"bg-emerald-50 text-emerald-700":"bg-amber-50 text-amber-700"}`}>{x[2]}</span></Link>)}</div></Card></div></MobiGestShell>}


function PerfilRouteBoundary() {
  return <RouteIndexBoundary pattern="/proprietarios/$id"><Perfil /></RouteIndexBoundary>;
}
