import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowLeft, CheckCircle2, KeyRound } from "lucide-react";
import { useState } from "react";
import { SuperAdminShell, SuperCard } from "../../../components/SuperAdminShell";

export const Route=createFileRoute("/super-admin/licencas/novo")({component:NovaLicenca});
function NovaLicenca(){
 const [done,setDone]=useState(false); const [municipality,setMunicipality]=useState("Lichinga"); const [plan,setPlan]=useState("Profissional"); const [start,setStart]=useState("2026-09-01"); const [end,setEnd]=useState("2027-08-31"); const [status,setStatus]=useState("Activa"); const [notes,setNotes]=useState("");
 if(done)return <SuperAdminShell title="Licença preparada" subtitle="A configuração da licença foi concluída."><SuperCard className="mx-auto max-w-2xl p-8 text-center"><div className="mx-auto flex h-14 w-14 items-center justify-center rounded-full bg-emerald-50 text-emerald-600"><CheckCircle2/></div><h2 className="mt-5 text-2xl font-bold">Licença {plan}</h2><p className="mt-2 text-sm text-slate-500">Município de {municipality}</p><p className="mt-5 text-sm text-slate-600">{start} → {end}</p><div className="mt-5 rounded-xl border border-amber-100 bg-amber-50 p-4 text-left text-sm leading-6 text-amber-900">Ainda não existe persistência no Supabase. Esta operação prepara a licença para a fase de dados reais.</div><Link to="/super-admin/licencas" className="mt-7 inline-flex rounded-xl bg-sky-600 px-5 py-3 text-sm font-semibold text-white">Voltar às licenças</Link></SuperCard></SuperAdminShell>;
 return <SuperAdminShell title="Nova licença" subtitle="Atribuir uma licença de utilização do MobiGest a um município."><Link to="/super-admin/licencas" className="mb-6 inline-flex items-center gap-2 text-sm text-slate-500"><ArrowLeft className="h-4 w-4"/> Licenças</Link><SuperCard className="mx-auto max-w-4xl p-7"><div className="flex items-start gap-4 border-b border-slate-100 pb-6"><div className="flex h-12 w-12 items-center justify-center rounded-xl bg-sky-50 text-sky-600"><KeyRound/></div><div><h2 className="text-xl font-bold">Dados da licença</h2><p className="mt-1 text-sm text-slate-500">A licença controla a utilização do software, não as taxas municipais dos veículos.</p></div></div><div className="mt-7 grid gap-5 md:grid-cols-2"><Select label="Município" value={municipality} setValue={setMunicipality} options={["Lichinga","Pemba"]}/><Select label="Plano" value={plan} setValue={setPlan} options={["Inicial","Profissional","Enterprise","Demonstração"]}/><Field label="Início" value={start} setValue={setStart} type="date"/><Field label="Fim" value={end} setValue={setEnd} type="date"/><Select label="Estado" value={status} setValue={setStatus} options={["Activa","Em configuração","Suspensa"]}/><Field label="Referência / observação" value={notes} setValue={setNotes} placeholder="Opcional"/></div><div className="mt-6 grid gap-3 md:grid-cols-3"><Info label="Limite de utilizadores" value={plan==="Inicial"?"10":plan==="Profissional"?"50":"Configurável"}/><Info label="Limite de veículos" value={plan==="Inicial"?"1 000":plan==="Profissional"?"5 000":"Configurável"}/><Info label="Módulos" value="Conforme plano"/></div><div className="mt-7 flex justify-end gap-3"><Link to="/super-admin/licencas" className="rounded-xl border border-slate-200 px-5 py-3 text-sm font-semibold">Cancelar</Link><button type="button" onClick={()=>setDone(true)} className="rounded-xl bg-sky-600 px-5 py-3 text-sm font-semibold text-white">Preparar licença</button></div></SuperCard></SuperAdminShell>;
}
function Field({label,value,setValue,type="text",placeholder=""}:{label:string;value:string;setValue:(v:string)=>void;type?:string;placeholder?:string}){return <label className="text-sm font-medium">{label}<input type={type} value={value} onChange={e=>setValue(e.target.value)} placeholder={placeholder} className="mt-2 h-11 w-full rounded-xl border border-slate-300 px-3 outline-none focus:border-sky-500"/></label>}
function Select({label,value,setValue,options}:{label:string;value:string;setValue:(v:string)=>void;options:string[]}){return <label className="text-sm font-medium">{label}<select value={value} onChange={e=>setValue(e.target.value)} className="mt-2 h-11 w-full rounded-xl border border-slate-300 px-3">{options.map(o=><option key={o}>{o}</option>)}</select></label>}
function Info({label,value}:{label:string;value:string}){return <div className="rounded-xl bg-slate-50 p-4"><p className="text-xs text-slate-400">{label}</p><p className="mt-1 text-sm font-semibold">{value}</p></div>}
